name: build

on: [push]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: 5.15.1
        dir: ${{ github.workspace }}/qt/
    - name: Install Linux dependencies
      run: |
        sudo apt-get install -y gperf libnss3-dev
    - name: Build QtWebEngine
      run: |
        git clone -b 5.15.1 https://github.com/qt/qtwebengine.git
        cd qtwebengine
        git submodule update --init
        qmake . -- -webengine-proprietary-codecs