name: build

on: [push]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: 5.15.1
        dir: ${{ github.workspace }}/qt/
    - name: Install Linux dependencies
      run: |
        sudo apt-get install '^libxcb.*-dev' libx11-xcb-dev libglu1-mesa-dev libxrender-dev libxi-dev libxkbcommon-dev libxkbcommon-x11-dev
        sudo apt-get install -y libxcursor-dev libxcomposite-dev libxdamage-dev libxrandr-dev libxtst-dev libxss-dev libdbus-1-dev libevent-dev libfontconfig1-dev libcap-dev libpulse-dev libudev-dev libpci-dev libnss3-dev libasound2-dev libegl1-mesa-dev gperf bison nodejs
    - name: Build QtWebEngine
      run: |
        git clone -b 5.15.1 https://github.com/qt/qtwebengine.git
        cd qtwebengine
        git submodule update --init
        qmake . -- -webengine-proprietary-codecs
        make
        make install
